### ISSUE TITLE
Following issue: setdefaultencoding

### ISSUE THREAD

**Issue by dscholtus** [luoliyan/incremental-reading-for-anki#1]
First thank you very much for working on this Haddon. I really do use it and it's amazing you can code this. Thank you very much!

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/mac/Library/Application Support/Anki2/addons/ir_addon.py", line 24, in <module>
  File "/Users/mac/Library/Application Support/Anki2/addons/ir/__init__.py", line 1, in <module>
  File "/Users/mac/Library/Application Support/Anki2/addons/ir/main.py", line 23, in <module>
AttributeError: 'module' object has no attribute 'setdefaultencoding'

**Comment by luoliyan** [comment]
Thanks very much for the report. I've made a change that I think should resolve this issue.

Let me know if it works for you.

**Comment by dscholtus** [comment]
It did solve it, thank you very much.
Btw: where did you learn to code python & Anki, I want to learn it myself and help you and other people.

**Comment by luoliyan** [comment]
I learned Python from [Dive Into Python 3](http://www.diveintopython3.net), which is free to read online. Python isn't my first programming language, so I'm not sure if that book is any good for beginners. It's written well enough, though.

As for writing add-ons, I mostly just looked at what other people were doing. There is nothing new under the sun, so if you want to do something, someone else has probably half done it for you already. If I get stuck, I'll check the [Anki source code](https://github.com/dae/anki).
