### ISSUE TITLE
Anki 1.2.x branch support.

### ISSUE THREAD

**Issue by JulyMorning** [luoliyan/incremental-reading-for-anki#11]
Please, take a look @ the compatibility with the reworked version of Anki, currently in beta:

— https://anki.tenderapp.com/discussions/beta-testing

**Comment by luoliyan** [comment]
This is in the pipeline. I've got it to the point where it's about 80% compatible. There are just a few things that don't work, because they are bit tricky to fix. But this is very high on my to-do list.

**Comment by luoliyan** [comment]
Hi again.

I've spent a few days working on this, and I think it's basically compatible now. If you're using Anki 2.1 and feel like testing, download the [anki21 development branch](https://github.com/luoliyan/incremental-reading-for-anki/archive/anki21.zip) and see how it goes.

From my own testing, there don't seem to be any major issues.
