### ISSUE TITLE
Incorrect scheduling (wrong cards rescheduled during review)

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#16]
I mix decks as described in https://github.com/aleksejrs/anki-2.0-vsa-and-ire#usage, and am getting that dialog, which seems to be completely pointless since the add-on knows where to extract and where to find the cards among which to organize this card.

**Comment by aleksejrs** [comment]
Hmm, apparently it means something.

Decks:
/
/::s
/::ir

/::s has a New card.
1. I go to "/" and rate the New card from /::s. Now it should be a Review card.
2. A few seconds to load the next card from /::ir.
3. I press "s" or "Esc" to stop reviewing.
The mentioned New card is New again.

**Comment by luoliyan** [comment]
Hi,

I'm not sure I understand the first part. That message should only occur when opening the organiser in a deck with no IR cards. If there are no IR cards, there is nothing organise.

The second part I will look into. If I understand correctly, you're saying that regular Anki cards are being reset if they are followed immediately by an IR card. That shouldn't happen.

**Comment by aleksejrs** [comment]
The first part:

Decks:
/ (root deck, empty)
/::s (normal Anki spaced repetition deck, Review/Learn/New)
/::ir (Incremental reading deck)

The current deck is "/", so IR cards are in the same global queue (or queue of queues) as the spaced repetition card that is reset.
There are three queues:
* Learn cards,
* Review cards,
* New cards (in /::s and its subdecks), then Incremental Reading cards (in /::ir).
The 2nd and the 3rd queues are intermingled with each other.

When I am reviewing and an IR card appears, the message appears.  Maybe it depends on the kind of the previous card, but after it happened once, that card was New.

**Comment by aleksejrs** [comment]
Now I am reviewing and two cards have been reset, but I didn't notice any message. Could have dismissed as the review limit message though.

**Comment by luoliyan** [comment]
You didn't miss anything. This is a serious bug, that I somehow didn't notice until now. Whenever you answer an IR card, the add-on reschedules the **_previous_** card, not the current one.

Give me a couple of days to come up with a decent solution for this. The scheduling code is the only part of the add-on that I haven't completely rewritten, so there's probably a lot I need to fix.

**Comment by luoliyan** [comment]
I've fixed that particular problem, but the scheduling code still needs a lot of work. It hasn't really changed since IR2, and I've been procrastinating about rewriting it because it's such a big job. It doesn't even use Qt widgets -- it's just a bunch of HTML and JavaScript in a webview. I'll put this at the top of my to-do list, but it'll probably take a few weeks.
