### ISSUE TITLE
Extracts refer to images by a full path

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#17]
Such images are not displayed. The bug holds over from IRead 2.

**Comment by luoliyan** [comment]
Can you give an example? What does the HTML of the card say, and where is the image stored?

**Comment by aleksejrs** [comment]
Original source:
`pre <img src="001.jpg"> post`

Select everything between "p" and "ost", then extract.

New source:

`p<span id="s15050502668" ir-bg-color="Green" ir-text-color="White"></span><font color="#ffffff" style="background-color: green;">re <img src="001.jpg" /> p</font><span id="e15050502668"></span>ost`

Extract:

`<span style="color: rgb(0, 0, 0);font-family: arial;font-size: 20px;font-variant: normal;letter-spacing: normal;line-height: normal;orphans: 2;text-align: center;text-indent: 0px;text-transform: none;white-space: normal;widows: 2;word-spacing: 0px;-webkit-text-size-adjust: auto;-webkit-text-stroke-width: 0px;background-color: rgb(255, 255, 255);display: inline !important;float: none">re<span class="Apple-converted-space">&nbsp;</span></span><img src="file:///home/user/.local/share/Anki2/test/collection.media/001.jpg" style="max-width: 95%; max-height: 95%; color: rgb(0, 0, 0); font-family: arial; font-size: 20px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" /><span style="color: rgb(0, 0, 0); font-family: arial; font-size: 20px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="Apple-converted-space">&nbsp;</span>p</span>`

**Comment by luoliyan** [comment]
This should be easy to fix. I'll try to make it happen over the weekend.

**Comment by luoliyan** [comment]
I'm still working on this. I'm having a bit of trouble reproducing the problem, but I'll get it done eventually.

**Comment by luoliyan** [comment]
This should be fixed. Let me know if it's not.
