### ISSUE TITLE
Incremental Reading Add-On: Change of Highlight background color

### ISSUE THREAD

**Issue by lizvoila** [luoliyan/incremental-reading-for-anki#2]
Amazing add-on for the record. Still trying to figure out how to put it to optimal use.
To sum up beforehand, the issues are:
1. What does this # icon do that "h" short-cutting highlight would not achieve?
2. Could we set the background and text color respectively when highlighting?

The issue is about the highlight background color, it seems that the auto one is pitch black and I do not see any editing options. (I have looked, real closely).
FYI, when using the "h" to highlight the text, it's not permanent once you exit the current card. There is a small # icon and clicking it the text would be "double" highlighted with the black color. That seems to the issue. 
Again, it's good add-on and thank you all for you work.
![review](https://cloud.githubusercontent.com/assets/23472458/21961519/85c831ee-db46-11e6-9cfa-7eaf8a33e2e3.png)

**Comment by luoliyan** [comment]
Thanks for the report. I'm not sure why the add-on is creating a black background. I assume you've chosen to highlight the text with that crimson(?) colour. In that case, it should not be changing the background colour at all. Currently the add-on only highlights the text _**or**_ the background with a custom colour, not both (at least in theory).

Do you know whether this problem existed with version 2 ([here](https://ankiweb.net/shared/info/355348508))? I may have introduced the problem when I modified the highlighting code.

In any case, I've been meaning to add support for setting the text colour and background colour separately, so I might look into doing that now. Might get two birds with one stone that way.

**Comment by luoliyan** [comment]
Sorry, I missed your first question.

The # icon is supposed to allow you to remove the highlighting from a section of text. However, it doesn't seem to work in version 2, and I haven't been able to make it work in version 3, despite a lot of effort. Currently it's in the "too hard" basket, but it's still on my to-do list.

**Comment by luoliyan** [comment]
Okay, so I've made an attempt to fix this. In the [development version](https://github.com/luoliyan/incremental-reading-for-anki/tree/dev), you can now select a text colour and a background colour for general highlighting and extraction, as well for quick add cards shortcuts.

Please download [this zip file](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip) and place "ir_addon.py" and the "ir" folder into your addons folder (overwriting the existing files).

Let me know if it helps.

**Comment by lizvoila** [comment]
Thanks. I am gonna try it out later tonight and give feedback ASAP.
1.The black background-highlight happened when I hit the # icon. The text was red coz I choose highlight text in the menu. So I figure this might the # thing going wrong.
2. Besides, any previous highlighting seems to be erased when re-entering the card. It would be helpful if it could retain its "marking history".
3.The card is altered when en-entering it. The "Context" filed obviously quoted the same card. 


![anki card screenshot](https://cloud.githubusercontent.com/assets/23472458/21973593/ba99e884-dbfc-11e6-9e1a-9214951b0627.png)

**Comment by luoliyan** [comment]
Pressing 'h' or 'x' should result in permanent highlighting, based on the colours you've chosen. Clicking # should change the highlighting to something different (black text on white background, in the development version), but this should **_not_** be permanent, because the function is broken. (I might consider removing the # until this is fixed, to avoid confusion.)

Anyway, some of the behaviour you describe is a bit puzzling to me. For example, it looks like you have duplicated headings. This was a problem with how version 2 did highlighting (because it copied the entire page back into the Text field), and which I thought I had fixed. I guess you have added to the card template, but do you have the following line somewhere?:

`<div class="ir-text">{{Text}}</div>`

That div around the Text field is necessary to tell the add-on what part of the page to process. If it's missing from the template, things will not work properly. If you'd like to post the card template here, I'll have a look at it.

Also, is there any chance you still have a previous version of IR in your addons folder? Can you check to make sure the following files are not there:

* Incremental\_Reading\_Extension.py
* View\_Size\_Adjust.py

If they are, they need to be deleted, because they will interfere with the new add-on. (Removing these old files automatically is something I'll put on my to-do list.)

**Comment by lizvoila** [comment]
1. Duplicated Headings. I have tweaked the template display a bit but the core" ir-text" lines are intact. The back template is as follows:

<div class="bar head">牌组名称 : {{Deck}}
</div>

{{#Title}}
<div class="section">
<div id="ir-text" class="items">{{Title}}</div>
</div>
{{/Title}}

{{#Text}}
<div class="section">
<div id="ir-text" class="items">{{Text}}</div>
</div>
{{/Text}}

<script type="text/javascript"src="_o3.js"></script>
 
Might me sending you my template if it’s not too much trouble for you to look into. 

2. Permanent highlight. I used the “h” shortcut and the highlight would disappear if I quit the card and re-enter. Maybe I could screen-record it, making it a gif. Normally I open the article/ anki card and do some reading, making highlight then I just click to return to the main deck. I have not used the answer buttons. Honestly speaking, I have no idea what their functions are. I know the basics of this supermemo incremental reading idea, but never used the Anki-addon upon which you’ve developed a new version. 

3. I do not have the incremental-reading-extension nor view-size-adjust py files in my add-on folder. I would try a control-enviroment test running only this add-on later.

Again, million thanks to you taking your personal time developing this add-on. It’s real helpful with so much potentials. 
Make it work. --Ultimate quote  from Time Gunn,

**Comment by luoliyan** [comment]
Thanks for your help with this. I only work on this add-on because I use it myself, and know it can be valuable when it works properly. Hopefully we can get to the bottom of the problem.

I think I've solved the issue with highlighting not being saved. It requires a slight change to your template, as well as a change to the add-on.

Can you replace this line in your template:
`<div id="ir-text" class="items">{{Text}}</div>`
with this:
`<div class="ir-text items">{{Text}}</div>`

And also remove id="ir-text" from this line:
`<div id="ir-text" class="items">{{Title}}</div>`

I've updated the add-on to allow for multiple classes (in your case, "items" and "ir-text"). You'll need to download the development version again ([link](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip)) and update the files.

**Comment by lizvoila** [comment]
【Feedback】
1. √ Template Tweak. I've changed it according to your advice and it works. 
2.× With the dev. version, the highlighting still is not permanent. 
3. √ The # icon is gone in the dev. version. 
4. √ Highlight color change. The dev version does support background and text highlight differentiation.

**Comment by luoliyan** [comment]
Quite strange, that. I'm able to reproduce the non-permanent highlighting problem by using your old template, but not with the tweaked template. As far as I can tell, the only reason highlighting wasn't being saved is because it needs to be class="ir-text", not id="ir-text" (the add-on searches for a class attribute).

On the PC, I've tried every way of exiting from a card, and highlighting is always preserved. I'm hoping this isn't a weird Mac-only thing.

Internally, the steps involved in highlighting are:
1. Mark the selected text
2 Highlight the text (which works for you)
3. Locate a div with class="ir-text"
4. Save the contents of that div to the Text field
5. Whenever the card is loaded, find all marked blocks of text and highlight them

Are you able to do the following for me:
1. Highlight a section of text
2. Click Edit
3. Click in the Text field
4. Choose Edit HTML from the menu (or press Ctrl+Shift+X)
5. Paste the HTML here for me to take a look at

If the HTML is correct, then it must be broken at step 5.

**Comment by lizvoila** [comment]
Ok, I’ve just done what you’ve asked. Went an extra step to reset my template to basic mode to exclude any conflict it my tweaked template might/could do to the display. 

 And it breaks in the second step. Here’s the step-by-step breakdown.
1. Done. Highlight a section of text.  


2. Fail. Right after this, I clicked the Edit button and the highlight is gone.

**Comment by luoliyan** [comment]
Can you post the HTML of the Text field. There might be something hidden there.

**Comment by lizvoila** [comment]
Here's the complete code of that highlighted part.

<div id="pages" style="margin-top: 0px; margin-right: 0px; margin-bottom: 1.5em; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; "><div class="page" id="page1" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: relative; "><div class="page_content" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; "><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 1.5em; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; ">La première ministre britannique doit dévoiler aujourd’hui sa stratégie pour quitter l’Union européenne.</p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 1.5em; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; "><span style="font-weight: bold">Annoncé avec tambours et trompettes, le discours que doit&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/prononcer/" title="Conjugaison du verbe prononcer" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">prononcer</a>&nbsp;Theresa May en fin de matinée, mardi 17&nbsp;janvier, est censé&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/pr%C3%A9ciser/" title="Conjugaison du verbe préciser" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">préciser</a>&nbsp;son plan pour le Brexit, à environ dix semaines du déclenchement de la procédure de divorce avec l’UE, qu’elle a annoncé pour la fin mars. Jusqu’à présent, la Première ministre a surtout répété des formules creuses, comme&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;Le Brexit veut&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/dire/" title="Conjugaison du verbe dire" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">dire</a>&nbsp;le Brexit&nbsp;»&nbsp;</em>ou<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">&nbsp;«&nbsp;Nous sortons de l’UE mais pas de l’<a href="http://www.lemonde.fr/europe/" title="Toute l’actualité Europe" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">Europe</a>&nbsp;»</em>.</span></p><div id="articleBody" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; "><p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Son intervention est destinée à&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/contrarier/" title="Conjugaison du verbe contrarier" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">contrarier</a>&nbsp;l’idée selon laquelle elle n’a en réalité aucun plan, comme l’a affirmé de façon explicite l’hebdomadaire&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">The Economist,</em>&nbsp;qui l’a surnommée&nbsp;<a href="http://www.economist.com/news/leaders/21713837-after-six-months-what-new-prime-minister-stands-still-unclearperhaps-even" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">«&nbsp;Theresa Maybe&nbsp;»</a>&nbsp;(«&nbsp;Theresa Peut-être&nbsp;»). Downing Street veut aussi&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/faire/" title="Conjugaison du verbe faire" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">faire</a>&nbsp;oublier l’épisode ravageur de la démission de l’ambassadeur britannique auprès de l’UE, critique à l’égard des orientations&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;brumeuses&nbsp;»</em>&nbsp;de M<sup style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">me</sup>&nbsp;May. Cette dernière veut enfin&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/prendre/" title="Conjugaison du verbe prendre" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">prendre</a>&nbsp;l’initiative avant l’arrêt de la Cour suprême britannique qui, attendu pour la semaine prochaine, va probablement l’obliger à&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/deuxieme-groupe/saisir/" title="Conjugaison du verbe saisir" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">saisir</a>&nbsp;le Parlement avant d’engager le Brexit, ce qu’elle ne souhaitait pas.</p><h2 style='margin: 2.28571em 0px 0.75em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 1.3125em; line-height: 1.15; font-family: "PT Serif"; vertical-align: baseline; text-align: left;'>Chantage</h2><p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">En octobre, la première ministre avait fixé deux lignes rouges&nbsp;: la maîtrise de la&nbsp;<a href="http://www.lemonde.fr/politique/" title="Toute l’actualité politique" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">politique</a>&nbsp;d’immigration des Européens au&nbsp;<a href="http://www.lemonde.fr/royaume-uni/" title="Toute l’actualité Royaume-Uni" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">Royaume-Uni</a>&nbsp;et la fin de la suprématie de la Cour de&nbsp;<a href="http://www.lemonde.fr/justice/" title="Toute l’actualité justice" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">justice</a>&nbsp;de l’<a href="http://www.lemonde.fr/union-europeenne/" title="Toute l’actualité Union européenne" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">Union européenne</a>&nbsp;(CJUE) sur les juridictions britanniques. La conséquence logique en est la sortie du marché unique, précisément régulé par la CJUE. M<sup style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">me</sup>&nbsp;May a aussi répété qu’elle ne se laisserait pas&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/enfermer/" title="Conjugaison du verbe enfermer" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">enfermer</a>&nbsp;dans l’alternative entre contrôle de l’immigration et accès au marché unique (deux prérogatives jugées incompatibles par les Vingt-Sept). Elle s’est fait fort de&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;négocier le meilleur accord&nbsp;possible&nbsp;»</em>. En menaçant dimanche l’UE de&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/transformer/" title="Conjugaison du verbe transformer" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">transformer</a>&nbsp;le Royaume-Uni en paradis fiscal, si l’Europe refusait de lui&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/ouvrir/" title="Conjugaison du verbe ouvrir" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">ouvrir</a>&nbsp;son marché, son ministre des&nbsp;<a href="http://www.lemonde.fr/finance/" title="Toute l’actualité finances" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">finances</a>, Philip Hammond, a nettement raidi le ton.</p><p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Lire aussi : &nbsp;&nbsp;<a href="http://www.lemonde.fr/europe/article/2017/01/16/union-europeenne-allemagne-otan-les-dirigeants-europeens-perplexes-face-aux-critiques-de-trump_5063470_3214.html" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">Les Européens ont leur destin «&nbsp;en main&nbsp;», répond Angela Merkel à Donald Trump</a></p><p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Theresa May confirmera-t-elle ce chantage&nbsp;? Précisera-t-elle ses objectifs&nbsp;? Les observateurs espèrent qu’elle détaillera sa position sur le système de contrôle de l’immigration, sur la nature des relations économiques qu’elle souhaite&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/nouer/" title="Conjugaison du verbe nouer" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">nouer</a>&nbsp;avec le continent,&nbsp;<a href="http://www.lemonde.fr/economie/article/2017/01/11/brexit-la-city-s-inquiete-pour-ses-emplois_5060853_3234.html" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">en particulier le positionnement de la City</a>. Mais rien n’est moins sûr.</p><p style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">En termes très généraux, les premiers éléments de son discours diffusés par Downing Street expriment l’ambition de&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/construire/" title="Conjugaison du verbe construire" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">construire</a>&nbsp;une<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">&nbsp;«&nbsp;Grande-<a href="http://www.lemonde.fr/bretagne/" title="Toute l’actualité Bretagne" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">Bretagne</a>&nbsp;mondiale&nbsp;»</em>&nbsp;à&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/partir/" title="Conjugaison du verbe partir" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">partir</a>&nbsp;des&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;opportunités&nbsp;»</em>&nbsp;qu’offre le Brexit, selon M<sup style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">me</sup>&nbsp;May.&nbsp;<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;Je veux que le Royaume-Uni émerge de cette période de changement plus fort, plus uni, plus juste et plus tourné vers l’extérieur que jamais&nbsp;»</em>, doit-elle&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/d%C3%A9clarer/" title="Conjugaison du verbe déclarer" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">déclarer</a>. S’adressant aux «&nbsp;continentaux&nbsp;», elle affirmera que l’<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">«&nbsp;intérêt massif&nbsp;»</em>&nbsp;de son pays est de&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/troisieme-groupe/voir/" title="Conjugaison du verbe voir" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">voir</a>&nbsp;l’UE<em style="margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">&nbsp;«&nbsp;réussir&nbsp;».&nbsp;</em>Pour que ce message amical, éloigné de celui de M. Hammond, soit bien relayé, les ambassadeurs à Londres des vingt-sept Etats de l’Union ont été invités à&nbsp;<a href="http://conjugaison.lemonde.fr/conjugaison/premier-groupe/%C3%A9couter/" title="Conjugaison du verbe écouter" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">écouter</a>&nbsp;solennellement la première ministre à Lancaster House, haut lieu de la&nbsp;<a href="http://www.lemonde.fr/diplomatie/" title="Toute l’actualité diplomatie" target="_blank" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(31, 9, 9); text-decoration: none;">diplomatie</a>&nbsp;britannique, à deux pas de Buckingham Palace.</p></div></div></div></div><div id="measure__lineHeight" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; position: absolute; top: -1000px; left: -1000px;">Measure</div><div id="measure__fontSize" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1; font-family: inherit; vertical-align: baseline; position: absolute; top: -1000px; left: -1000px;">Measure</div><div id="relatedNotes" class="bottom" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; direction: ltr !important; unicode-bidi: bidi-override !important; text-align: left !important;"><div id="relatedNotes__separator" class="separator" style="margin: 0px; padding: 1.5em 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1; font-family: inherit; vertical-align: baseline; position: relative; height: 1em; text-align: center;"><div class="separatorLine setTextColorAsBackgroundColor" style='margin: 0px; padding: 0px 4em; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: "PT Serif"; vertical-align: baseline; background: -webkit-linear-gradient(0deg, rgb(243, 242, 238) 1%, rgb(31, 9, 9) 50%, rgb(243, 242, 238) 99%); position: absolute; left: -4em; top: 32px; z-index: 10; width: 576px; height: 0.1em; opacity: 0.5; color: rgb(31, 9, 9); letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;'></div><div class="separatorLabel setBackgroundColor" style='margin-top: 0px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding: 0px 0.5em; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: "PT Serif"; vertical-align: baseline; background-color: rgb(243, 242, 238); position: relative; z-index: 100; display: inline; color: rgb(31, 9, 9); letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;'></div></div></div>

**Comment by luoliyan** [comment]
Thanks. Let me play around with this.

**Comment by luoliyan** [comment]
Still haven't solved this yet, but I've made a modified main.py that might help pinpoint where things go wrong. Please download [main.zip](https://github.com/luoliyan/incremental-reading-for-anki/files/710723/main.zip) and replace ir/main.py with this modified one.

Try to highlight some text, exit out of the card, then go back into the card. On a fresh card with no highlighting, you should first get a pop-up window saying the highlighting can't be found. After pressing 'h', you should no longer get any pop-up windows for that card. If you do, let me know what they say.
