### ISSUE TITLE
Only two zoom levels / one step

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#22]
I installed 4.2.7 from master onto Anki 2.1b16, and I have only two zoom levels (one step that is configured in the addon). Why?

**Comment by luoliyan** [comment]
Damien made a change to the hook I was using. I will update the add-on soon.

**Comment by luoliyan** [comment]
Should be fixed now.

**Comment by aleksejrs** [comment]
Doesn't work.

**Comment by luoliyan** [comment]
Well, then I fixed something different.

What exactly are you trying to do?

**Comment by aleksejrs** [comment]
Was the fix https://github.com/luoliyan/incremental-reading-for-anki/commit/b02d26ba485ef6b1c8d6729895a8497bb42ad4d5 ?

**Comment by luoliyan** [comment]
Beta 16 changed the `prepareQuestion` hook, and that broke most of the add-on. b02d26b restored the correct behaviour.

**Comment by aleksejrs** [comment]
It works on IR3 cards, but not on other cards.

**Comment by luoliyan** [comment]
Okay, that's weird. I don't use the zoom with non-IR cards, so I don't know when that stopped working. It certainly works fine on Anki 2.0.

I'll look into it.

**Comment by luoliyan** [comment]
This should be fixed. (Looks like Qt5 doesn't tell the truth about the current zoomFactor.)
