### ISSUE TITLE
Space bar and number keys do not press the "Show answer" and rating buttons

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#23]
Anki 2.1, master https://github.com/luoliyan/incremental-reading-for-anki/commit/4e5d74f56a6c7cc583139bc157284b85b56fb536

**Comment by luoliyan** [comment]
I think I have fixed this now (aa55283).

**Comment by aleksejrs** [comment]
Seems to work, thanks!
