### ISSUE TITLE
[dataloss] Support undo of deletion

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#24]
It's very easy to delete (`z`) when you want to extract (`x`).

**Comment by luoliyan** [comment]
I have written the code to support undo for deletion as well as highlighting. I am planning to update the add-on tomorrow.

**Comment by luoliyan** [comment]
This is done. Press `u` to undo any changes.

**Comment by aleksejrs** [comment]
Works, thanks!
