### ISSUE TITLE
Do not try to download a page or a feed when no URL is given.

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading-for-anki#28]
Especially when I pressed Esc without entering an URL.

**Comment by luoliyan** [comment]
Fixed.

**Comment by aleksejrs** [comment]
Have you tested it?  It doesn't seem to have changed anything (I checked that the change was applied to importer.py in my ~/.local/share/Anki2/addons21/1152164089 ).

**Comment by aleksejrs** [comment]
Works, thanks.

Although if I do enter an URL and press Esc, maybe it still shouldn't try.

**Comment by luoliyan** [comment]
That would be harder to change. I would need to keep track of how the window is closed, which I currently don't.

I'll put it on my to-do list.
