### ISSUE TITLE
Delete text in an article

### ISSUE THREAD

**Issue by kprimice** [luoliyan/incremental-reading-for-anki#3]
Is it possible to delete text in an article?
It can be useful to delete garbage and/or uninteresting text.

**Comment by luoliyan** [comment]
It's not possible at the moment, but it will be easy to add this feature. I've always just highlighted anything I don't want to read, but I can see why some people would prefer to delete it.

Check back here tomorrow and I'll have something for you to try.

**Comment by kprimice** [comment]
Wow, thank you!

**Comment by luoliyan** [comment]
I've updated the add-on. If you're game, download the development version ([click here](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip)), and extract to your add-ons folder.

Highlight some text you want to delete, then press the "r" key. ("r" for "remove"; I wanted "d" for "delete", but Anki overrides that shortcut.)

I haven't tested this very much, but it seems to work. Let me know how it goes.

**Comment by dscholtus** [comment]
luoliyan thanks very much, I love this addon with the delete function added!
I have another question, with extraction would it be possible to extract to a different anki Deck?

For example I have two decks: Books & subarticles.
In books I have the long articles and in the second subarticle deck I would like to have the extracted pieces.

Thanks again for your hard work!

**Comment by luoliyan** [comment]
Something I used for a while was:
* IR3 model has an extra field called "destination"
* When you press 'x', text is extracted to to the deck in "destination"

Does that sound like what you have in mind? Because that should be easy enough

**Comment by dscholtus** [comment]
Thanks for the response!

The field ‘destination’ was not there by default..
I have made a field called destination and named it all to the Deck I want to go, but it is not working.

Thanks again for your work!

**Comment by luoliyan** [comment]
It's a work in progress. I haven't added it to GitHub yet. I'll try to get something working by the end of the week

**Comment by luoliyan** [comment]
Give the [development version](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip) another try. Go to the "Extraction" tab in settings, an choose a destination deck for extracts.

Let me know how it goes.

**Comment by dscholtus** [comment]
Hi sorry,

Works great thanks a lot!

**Comment by luoliyan** [comment]
No problem :-)
