### ISSUE TITLE
Attribute Error after installing the newest extension supporting the remove key (r)

### ISSUE THREAD

**Issue by pizzooid** [luoliyan/incremental-reading-for-anki#4]
This Error occurs after finishing the learning session:

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/main.py", line 629, in keyPressEvent
    if self.keyHandler(evt):
  File "/usr/share/anki/anki/hooks.py", line 56, in repl
    return new(*args, **kwargs)
  File "/home/pietro/Documents/Anki/addons/ir/main.py", line 791, in keyHandler
    if self.card.note().model()['name'] == IR_MODEL_NAME:
AttributeError: 'NoneType' object has no attribute 'note'
```

Keep up the great work!

**Comment by luoliyan** [comment]
Thanks. I think you might have downloaded before all the files were updated. Let me know if it happens with the [new version](https://github.com/luoliyan/incremental-reading-for-anki/archive/master.zip).

**Comment by luoliyan** [comment]
I haven't been able to reproduce this, but I've made a change that should prevent it from happening. The [latest version](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip) should not have this problem.
